/**
 * PlotToon agent guide generator (#277).
 *
 * Mirrors plotlink-ows's `app/lib/generate-claude-md.ts` pattern: a
 * versioned markdown file with the live app's API surface, file
 * conventions, and workflow rules. Written to the project root so
 * Claude / Codex pick it up when launched from that cwd; refreshed on
 * outdated content.
 *
 * The generator is intentionally separated from the file-system write
 * so callers can unit-test the content + test the refresh logic
 * without touching real filesystems.
 */

import fs from 'node:fs/promises'
import path from 'node:path'

/**
 * Bump this when guide content changes. The version is stamped in the
 * first line so the refresh check can detect outdated files written by
 * an older PlotToon build. Independent of package.json — the guide
 * version tracks content, not app releases.
 */
export const PLOTTOON_AGENT_GUIDE_VERSION = '1.0.0'

/**
 * Filename written under the project root. Both Claude CLI (`CLAUDE.md`
 * auto-discovery) and Codex CLI (`AGENTS.md` auto-discovery) read other
 * markdown files when they're cited in those files; the project's
 * existing `AGENTS.md` references this guide so both runtimes will
 * load it.
 */
export const PLOTTOON_AGENT_GUIDE_FILENAME = 'PLOTTOON_AGENT_GUIDE.md'

export interface AgentGuideGeneratorContext {
  /** Project's `meta.name`. Used in the header + workflow examples. */
  projectName: string
}

export function generatePlotToonAgentGuide(context: AgentGuideGeneratorContext): string {
  const safeName = context.projectName.trim() || 'this project'
  return `# PlotToon — Agent Guide for ${safeName} (v${PLOTTOON_AGENT_GUIDE_VERSION})

> Auto-generated by PlotToon. Do not edit manually — your edits will be
> overwritten on the next refresh. PlotToon refreshes this file when
> the version stamp on the first line differs from the running app.

You are an AI coding agent (Claude or Codex) working inside a PlotToon
webtoon project. PlotToon is a desktop Electron app that orchestrates
the writing → image-generation → lettering/editor → publish flow.
This file describes the live app capabilities you can rely on, the
canonical data shapes, and the rules you must follow.

## 1. Workflow overview

The end-to-end PlotToon flow:

1. **Structure** — author writes \`structure.md\` describing the story
   arc, characters, themes.
2. **Plot / cut plan** — author or agent writes the cut list into
   \`plots/<plot-slug>/cuts.json\` (the canonical data file).
3. **Clean image generation** — the agent generates background art for
   each cut (clean images — no text, no speech bubbles unless
   explicitly requested) and saves them to the expected output path.
4. **App lettering / editor** — the human user opens PlotToon's editor
   to add speech bubbles, narration overlays, and per-cut text on top
   of the clean images. The agent does **not** add lettering.
5. **Export** — PlotToon flattens cuts + overlays into webp/jpeg
   exports under \`exports/\` (build artifacts).
6. **Publish** — PlotToon uploads the export to PlotLink (IPFS via
   PlotLink Base contracts) and records the on-chain tx + storyline id
   in local publish metadata.

## 2. Canonical data: \`cuts.json\`

Each plot lives under \`plots/<plot-slug>/\` and its \`cuts.json\` is the
**single source of truth**. Derived views (e.g. \`plot-text.md\`) are
generated FROM \`cuts.json\` — never edited directly.

Cut id convention: \`cut-NNN\` zero-padded (e.g. \`cut-001\`, \`cut-014\`).

Minimal cut shape:

\`\`\`json
{
  "plotTitle": "Episode 1",
  "cuts": [
    {
      "id": "cut-001",
      "order": 0,
      "status": "draft",
      "direction": "Establishing shot of the city skyline at dusk.",
      "dialogue": "",
      "narration": "",
      "overlays": [],
      "imageState": {
        "status": "pending",
        "path": null,
        "prompt": null,
        "seed": null
      }
    }
  ]
}
\`\`\`

### Safe \`cuts.json\` edits

- **Always read first**: load the file, mutate the in-memory object,
  write the whole file back. Never append or hand-edit partial JSON.
- **Validate**: PlotToon's writer rejects malformed \`cuts.json\`. Keep
  every cut entry shape-complete (no missing required keys).
- **Stable order**: the \`order\` field drives sort. When inserting a
  cut, reflow the \`order\` values of subsequent cuts.
- **Per-cut imageState**:
  - \`status: "pending"\` for new cuts
  - \`status: "done"\` + \`path: "plots/<slug>/assets/<cut>/clean-vNNN.webp"\`
    after generation
  - \`status: "failed"\` + reason in \`revisionNotes\` if generation
    errored.
- **Never** create a second source of truth (e.g. a separate
  \`scenes.json\`). Derive instead.

## 3. Clean image generation

The agent generates **clean** background images for each cut. Clean
means:

- **No speech bubbles, no captions, no text overlays.** Lettering
  belongs to the human editor flow (step 4) — the app composites it on
  top of your clean image.
- Only render text if the user explicitly asks for it (e.g. an
  in-scene sign or graffiti that's part of the artwork).
- Use a consistent style across cuts in the same plot — reference the
  project's \`style-guide.md\` if it exists.

### Output path

Save generated images under the plot's \`assets/<cutId>/\` folder with
a zero-padded version number:

\`\`\`
plots/<plot-slug>/assets/<cut-id>/clean-vNNN.webp
\`\`\`

- \`<plot-slug>\` matches the plot folder name.
- \`<cut-id>\` matches \`cuts.json\` (e.g. \`cut-001\`).
- \`vNNN\` starts at \`v001\` and increments on regeneration.
- Prefer WebP; JPEG is the acceptable fallback.

After writing the file, update \`cuts.json\` with the new \`imageState\`
(see §2).

## 4. AtlasCloud (advanced image backend) — opt-in env bridge

PlotToon supports AtlasCloud-style providers as an **advanced
agent-managed** option. The provider account + API key are entirely
user-owned; PlotToon never stores them.

### Before the bridge is enabled

By default, PlotToon's agent env sanitizer denies all \`_API_KEY\`
variables. \`ATLASCLOUD_API_KEY\` is NOT in your environment. Do not
ask the user to paste their API key into chat or any project file.

### When the user enables the bridge (#276)

The user can toggle the bridge on at **AtlasCloud Backend Guide →
Env bridge (opt-in)** in PlotToon. When enabled AND the user has
\`ATLASCLOUD_API_KEY\` set in their shell, PlotToon forwards the
single key into your process env at launch. You can read it via
\`process.env.ATLASCLOUD_API_KEY\` (or your runtime's equivalent).

- Always read the key from the environment — never request it from the
  user in chat, never write it to a project file or log.
- If the key is missing from \`process.env\`, do not retry or guess —
  surface the situation in chat and ask the user to enable the bridge
  or set the env var.
- Treat the key as a write-only sink: pass it to your HTTP client and
  never echo, log, or persist it.

### AtlasCloud output flow

1. Generate the image via the provider.
2. Save it to \`plots/<plot-slug>/assets/<cut-id>/clean-vNNN.webp\`
   (see §3).
3. Update \`cuts.json\` with the new \`imageState\` (status, path,
   backend, model, prompt, attempts).
4. The user will open the editor to add lettering — your job ends at
   the clean image.

## 5. Manual editor handoff

PlotToon's editor is where the **human user** adds speech bubbles,
narration overlays, panel borders, and any per-cut text. The agent
should:

- Hand off to the editor by setting the cut's \`imageState.status\` to
  \`"done"\` with the correct \`path\`.
- Not try to render lettering inside the generated image.
- Not modify exports — those are built by PlotToon's export pipeline
  after the user finishes lettering.
- When asked for revisions, regenerate the clean image with a higher
  \`vNNN\` and update \`cuts.json\` \`imageState.path\` to the new file.

## 6. What the agent must never touch

- \`exports/\` — build artifacts. PlotToon regenerates them; agent
  edits will be clobbered or invalidate downstream publish.
- \`project.json\` — project metadata. Only edit on explicit user
  request, and never the \`wallet\` field (set by PlotToon during
  project creation per the wallet-scoping work in #220).
- Wallet material — private keys, mnemonics, passphrases, vault
  paths, OWS internal wallet names. None are accessible from the
  project tree by design; do not try to discover them.
- Publish signatures + the on-chain transactions PlotToon constructs
  (\`publish:execute\`, \`royalty:claim\`, \`agent:register\`). These
  flows are signer-gated by PlotToon's main process; agent involvement
  is read-only.
- Private env vars — anything matching \`_API_KEY\`, \`_TOKEN\`,
  \`_SECRET\`, \`PRIVATE_*\`, \`WALLET_*\`, \`MNEMONIC\`, etc. is
  intentionally stripped from the agent environment.

## 7. Project file layout

\`\`\`
${safeName}/
├── project.json              # Project metadata (do not edit)
├── structure.md              # Story arc outline
├── genesis.md                # Origin / goals
├── style-guide.md            # Visual style reference (optional)
├── AGENTS.md                 # Static rules + pointer to this file
├── PLOTTOON_AGENT_GUIDE.md   # This file (auto-generated, versioned)
├── .publish-status.json      # Publish state
├── characters/               # Character definitions
└── plots/
    └── <plot-slug>/
        ├── cuts.json         # Canonical cut data
        ├── plot-text.md      # Generated from cuts.json (do not edit)
        ├── assets/
        │   └── <cut-id>/
        │       └── clean-vNNN.webp
        └── exports/          # Build artifacts (do not touch)
\`\`\`

## 8. Refresh policy

The first line of this file carries the guide version. PlotToon
checks that version on project open / agent launch and regenerates
this file when the version differs. Do not depend on edits surviving
across PlotToon restarts.
`
}

export async function writeOrRefreshProjectAgentGuide(
  projectRoot: string,
  context: AgentGuideGeneratorContext
): Promise<{ updated: boolean; path: string }> {
  const filePath = path.join(projectRoot, PLOTTOON_AGENT_GUIDE_FILENAME)
  const expectedVersionStamp = `(v${PLOTTOON_AGENT_GUIDE_VERSION})`
  try {
    const raw = await fs.readFile(filePath, 'utf-8')
    const firstLine = raw.split('\n')[0] ?? ''
    if (firstLine.includes(expectedVersionStamp)) {
      return { updated: false, path: filePath }
    }
  } catch {
    // File missing or unreadable; fall through to write.
  }
  const content = generatePlotToonAgentGuide(context)
  await fs.writeFile(filePath, content, 'utf-8')
  return { updated: true, path: filePath }
}
